# ekf.yaml
ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true

    # Frame settings (adjust these as needed for your robot)
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # If you have wheel odometry, add it here (example below):
    # odom0: /odom
    # odom0_config: [true,  true,  true,
    #                false, false, false,
    #                false, false, false,
    #                false, false, false,
    #                false, false, false]
    # odom0_differential: false

    # IMU settings (we’re fusing IMU data from /imu)
    imu0: /imu
    imu0_config: [false, false, false,  # position x, y, z (not used)
                  true,  true,  true,   # orientation x, y, z are used
                  false, false, false,  # linear velocity x, y, z (not used)
                  false, false, false,  # angular velocity x, y, z (not used)
                  false, false, false]  # accelerometer data (if desired)
    imu0_differential: false
    imu0_relative: true
